import type { Metadata } from "next";
import localFont from "next/font/local";
import { fetchUser } from "modules/fetchServer";
import { App_Dev, Header_App, App_Menu, Header_Socket, App_Footer } from "components/app";

import "./globals.css";
import "@styles/styles.scss"
import "@styles/variables.scss"
import "components/app/app.css";
import 'components/chat/chat.css';
import "components/board/board.css"
import "components/room/room.css"

import Script from "next/script";

const notoSans = localFont({
    src: [
        { path: "./fonts/NotoSansKR-Regular.woff2", weight: "400", style: "normal" },
        { path: "./fonts/NotoSansKR-Bold.woff2", weight: "700", style: "bold" },
    ],
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const $USER = await fetchUser();
    
    return (<html lang="ko">
        <Script strategy="afterInteractive" src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP}&libraries=clusterer,services&autoload=false`}/>
        <body className={notoSans.className}>
            <Header_App user={$USER.user}/>
            <Header_Socket/>
            <App_Menu/>
            <main className="layout_main">{children}</main>
            <App_Footer/>
            {process.env.NODE_ENV === 'development' && <App_Dev/>}
        </body>
    </html>);
}
